var annotated =
[
    [ "Artificiel", "class_artificiel.html", "class_artificiel" ],
    [ "ArtificielDames", "class_artificiel_dames.html", "class_artificiel_dames" ],
    [ "ArtificielOthello", "class_artificiel_othello.html", "class_artificiel_othello" ],
    [ "Case", "class_case.html", "class_case" ],
    [ "Controlleur", "class_controlleur.html", "class_controlleur" ],
    [ "ControlleurConsole", "class_controlleur_console.html", "class_controlleur_console" ],
    [ "ControlleurGTK", "class_controlleur_g_t_k.html", "class_controlleur_g_t_k" ],
    [ "Coup", "class_coup.html", "class_coup" ],
    [ "CoupDames", "class_coup_dames.html", "class_coup_dames" ],
    [ "CoupOthello", "class_coup_othello.html", "class_coup_othello" ],
    [ "DameDames", "class_dame_dames.html", "class_dame_dames" ],
    [ "EtatPieceDames", "class_etat_piece_dames.html", "class_etat_piece_dames" ],
    [ "Humain", "class_humain.html", "class_humain" ],
    [ "Jeu", "class_jeu.html", "class_jeu" ],
    [ "JeuDames", "class_jeu_dames.html", "class_jeu_dames" ],
    [ "JeuOthello", "class_jeu_othello.html", "class_jeu_othello" ],
    [ "Joueur", "class_joueur.html", "class_joueur" ],
    [ "Piece", "class_piece.html", "class_piece" ],
    [ "PieceDames", "class_piece_dames.html", "class_piece_dames" ],
    [ "PieceOthello", "class_piece_othello.html", "class_piece_othello" ],
    [ "PionDames", "class_pion_dames.html", "class_pion_dames" ],
    [ "Plateau", "class_plateau.html", "class_plateau" ],
    [ "PlateauDames", "class_plateau_dames.html", "class_plateau_dames" ],
    [ "PlateauOthello", "class_plateau_othello.html", "class_plateau_othello" ],
    [ "VueJeu", "class_vue_jeu.html", "class_vue_jeu" ],
    [ "VueJeuConsole", "class_vue_jeu_console.html", "class_vue_jeu_console" ],
    [ "VueJeuConsoleDames", "class_vue_jeu_console_dames.html", "class_vue_jeu_console_dames" ],
    [ "VueJeuConsoleOthello", "class_vue_jeu_console_othello.html", "class_vue_jeu_console_othello" ],
    [ "VueJeuGTK", "class_vue_jeu_g_t_k.html", "class_vue_jeu_g_t_k" ],
    [ "VueJeuGTKDames", "class_vue_jeu_g_t_k_dames.html", "class_vue_jeu_g_t_k_dames" ],
    [ "VueJeuGTKOthello", "class_vue_jeu_g_t_k_othello.html", "class_vue_jeu_g_t_k_othello" ],
    [ "VuePrincipale", "class_vue_principale.html", "class_vue_principale" ],
    [ "VuePrincipaleConsole", "class_vue_principale_console.html", "class_vue_principale_console" ],
    [ "VuePrincipaleGTK", "class_vue_principale_g_t_k.html", "class_vue_principale_g_t_k" ]
];